-- Seed inicial de paises ISO para Mundial 2026 y casos deportivos FIFA.
-- countries es ISO-first: code_alpha2 es la PK canonica.
-- FIFA/IOC son metadata deportiva, nunca claves primarias.

begin;

insert into countries (
  code_alpha2,
  code_alpha3,
  numeric_code,
  fifa_code,
  ioc_code,
  default_name,
  names,
  official_names,
  region,
  subregion,
  continent,
  timezone_default,
  timezones,
  currency_code,
  currency_name,
  flag_emoji,
  is_fifa_member,
  is_sovereign,
  payload
) values
('AR','ARG','032','ARG','ARG','Argentina','{"es":"Argentina","en":"Argentina"}','{"es":"Republica Argentina","en":"Argentine Republic"}','Americas','South America','SA','America/Argentina/Buenos_Aires',array['America/Argentina/Buenos_Aires'],'ARS','Argentine Peso','🇦🇷',true,true,'{"sports":{"confederation":"CONMEBOL"}}'),
('AU','AUS','036','AUS','AUS','Australia','{"es":"Australia","en":"Australia"}','{"en":"Commonwealth of Australia"}','Oceania','Australia and New Zealand','OC','Australia/Sydney',array['Australia/Sydney','Australia/Melbourne','Australia/Brisbane','Australia/Perth','Australia/Adelaide','Australia/Darwin','Australia/Hobart'],'AUD','Australian Dollar','🇦🇺',true,true,'{"sports":{"confederation":"AFC"}}'),
('AT','AUT','040','AUT','AUT','Austria','{"es":"Austria","en":"Austria"}','{"es":"Republica de Austria","en":"Republic of Austria"}','Europe','Western Europe','EU','Europe/Vienna',array['Europe/Vienna'],'EUR','Euro','🇦🇹',true,true,'{"sports":{"confederation":"UEFA"}}'),
('BE','BEL','056','BEL','BEL','Belgica','{"es":"Belgica","en":"Belgium"}','{"es":"Reino de Belgica","en":"Kingdom of Belgium"}','Europe','Western Europe','EU','Europe/Brussels',array['Europe/Brussels'],'EUR','Euro','🇧🇪',true,true,'{"sports":{"confederation":"UEFA"}}'),
('BA','BIH','070','BIH','BIH','Bosnia y Herzegovina','{"es":"Bosnia y Herzegovina","en":"Bosnia and Herzegovina"}','{"en":"Bosnia and Herzegovina"}','Europe','Southern Europe','EU','Europe/Sarajevo',array['Europe/Sarajevo'],'BAM','Bosnia and Herzegovina Convertible Mark','🇧🇦',true,true,'{"sports":{"confederation":"UEFA"},"aliases":["Bosnia","Bosnia-Herzegovina"]}'),
('BR','BRA','076','BRA','BRA','Brasil','{"es":"Brasil","en":"Brazil"}','{"es":"Republica Federativa del Brasil","en":"Federative Republic of Brazil"}','Americas','South America','SA','America/Sao_Paulo',array['America/Sao_Paulo','America/Manaus','America/Fortaleza','America/Recife','America/Cuiaba'],'BRL','Brazilian Real','🇧🇷',true,true,'{"sports":{"confederation":"CONMEBOL"}}'),
('CA','CAN','124','CAN','CAN','Canada','{"es":"Canada","en":"Canada"}','{"en":"Canada"}','Americas','Northern America','NA','America/Toronto',array['America/Toronto','America/Vancouver','America/Edmonton','America/Winnipeg','America/Halifax','America/St_Johns'],'CAD','Canadian Dollar','🇨🇦',true,true,'{"sports":{"confederation":"CONCACAF"}}'),
('CV','CPV','132','CPV','CPV','Cabo Verde','{"es":"Cabo Verde","en":"Cape Verde"}','{"es":"Republica de Cabo Verde","en":"Republic of Cabo Verde"}','Africa','Western Africa','AF','Atlantic/Cape_Verde',array['Atlantic/Cape_Verde'],'CVE','Cape Verdean Escudo','🇨🇻',true,true,'{"sports":{"confederation":"CAF"}}'),
('CL','CHL','152','CHI','CHI','Chile','{"es":"Chile","en":"Chile"}','{"es":"Republica de Chile","en":"Republic of Chile"}','Americas','South America','SA','America/Santiago',array['America/Santiago','Pacific/Easter'],'CLP','Chilean Peso','🇨🇱',true,true,'{"sports":{"confederation":"CONMEBOL"}}'),
('CO','COL','170','COL','COL','Colombia','{"es":"Colombia","en":"Colombia"}','{"es":"Republica de Colombia","en":"Republic of Colombia"}','Americas','South America','SA','America/Bogota',array['America/Bogota'],'COP','Colombian Peso','🇨🇴',true,true,'{"sports":{"confederation":"CONMEBOL"}}'),
('CD','COD','180','COD','COD','Congo DR','{"es":"Congo DR","en":"DR Congo"}','{"es":"Republica Democratica del Congo","en":"Democratic Republic of the Congo"}','Africa','Middle Africa','AF','Africa/Kinshasa',array['Africa/Kinshasa','Africa/Lubumbashi'],'CDF','Congolese Franc','🇨🇩',true,true,'{"sports":{"confederation":"CAF"},"aliases":["DR Congo","Congo DR"]}'),
('CW','CUW','531','CUW',null,'Curazao','{"es":"Curazao","en":"Curacao","nl":"Curacao"}','{"en":"Country of Curacao","nl":"Land Curacao"}','Americas','Caribbean','NA','America/Curacao',array['America/Curacao'],'ANG','Netherlands Antillean Guilder','🇨🇼',true,false,'{"sports":{"confederation":"CONCACAF"},"iso_note":"Constituent country within the Kingdom of the Netherlands","aliases":["Curaçao","Curacao"]}'),
('CZ','CZE','203','CZE','CZE','Republica Checa','{"es":"Republica Checa","en":"Czechia"}','{"en":"Czech Republic"}','Europe','Eastern Europe','EU','Europe/Prague',array['Europe/Prague'],'CZK','Czech Koruna','🇨🇿',true,true,'{"sports":{"confederation":"UEFA"},"aliases":["Czechia","Czech Republic"]}'),
('DZ','DZA','012','ALG','ALG','Argelia','{"es":"Argelia","en":"Algeria"}','{"es":"Republica Argelina Democratica y Popular","en":"People''s Democratic Republic of Algeria"}','Africa','Northern Africa','AF','Africa/Algiers',array['Africa/Algiers'],'DZD','Algerian Dinar','🇩🇿',true,true,'{"sports":{"confederation":"CAF"}}'),
('EC','ECU','218','ECU','ECU','Ecuador','{"es":"Ecuador","en":"Ecuador"}','{"es":"Republica del Ecuador","en":"Republic of Ecuador"}','Americas','South America','SA','America/Guayaquil',array['America/Guayaquil','Pacific/Galapagos'],'USD','US Dollar','🇪🇨',true,true,'{"sports":{"confederation":"CONMEBOL"}}'),
('EG','EGY','818','EGY','EGY','Egipto','{"es":"Egipto","en":"Egypt"}','{"es":"Republica Arabe de Egipto","en":"Arab Republic of Egypt"}','Africa','Northern Africa','AF','Africa/Cairo',array['Africa/Cairo'],'EGP','Egyptian Pound','🇪🇬',true,true,'{"sports":{"confederation":"CAF"}}'),
('ES','ESP','724','ESP','ESP','Espana','{"es":"Espana","en":"Spain"}','{"es":"Reino de Espana","en":"Kingdom of Spain"}','Europe','Southern Europe','EU','Europe/Madrid',array['Europe/Madrid','Atlantic/Canary'],'EUR','Euro','🇪🇸',true,true,'{"sports":{"confederation":"UEFA"}}'),
('FR','FRA','250','FRA','FRA','Francia','{"es":"Francia","en":"France"}','{"es":"Republica Francesa","en":"French Republic"}','Europe','Western Europe','EU','Europe/Paris',array['Europe/Paris'],'EUR','Euro','🇫🇷',true,true,'{"sports":{"confederation":"UEFA"}}'),
('GB','GBR','826',null,'GBR','Reino Unido','{"es":"Reino Unido","en":"United Kingdom"}','{"es":"Reino Unido de Gran Bretana e Irlanda del Norte","en":"United Kingdom of Great Britain and Northern Ireland"}','Europe','Northern Europe','EU','Europe/London',array['Europe/London'],'GBP','Pound Sterling','🇬🇧',false,true,'{"sports":{"note":"ISO country has multiple FIFA associations","fifa_associations":[{"name":"England","fifa_code":"ENG","is_fifa_member":true},{"name":"Scotland","fifa_code":"SCO","is_fifa_member":true},{"name":"Wales","fifa_code":"WAL","is_fifa_member":true},{"name":"Northern Ireland","fifa_code":"NIR","is_fifa_member":true}]},"aliases":["England","Scotland","Wales","Northern Ireland","Inglaterra","Escocia","Gales","Irlanda del Norte"]}'),
('DE','DEU','276','GER','GER','Alemania','{"es":"Alemania","en":"Germany"}','{"es":"Republica Federal de Alemania","en":"Federal Republic of Germany"}','Europe','Western Europe','EU','Europe/Berlin',array['Europe/Berlin'],'EUR','Euro','🇩🇪',true,true,'{"sports":{"confederation":"UEFA"},"aliases":["Germany","Deutschland"]}'),
('GH','GHA','288','GHA','GHA','Ghana','{"es":"Ghana","en":"Ghana"}','{"en":"Republic of Ghana"}','Africa','Western Africa','AF','Africa/Accra',array['Africa/Accra'],'GHS','Ghanaian Cedi','🇬🇭',true,true,'{"sports":{"confederation":"CAF"}}'),
('HR','HRV','191','CRO','CRO','Croacia','{"es":"Croacia","en":"Croatia"}','{"es":"Republica de Croacia","en":"Republic of Croatia"}','Europe','Southern Europe','EU','Europe/Zagreb',array['Europe/Zagreb'],'EUR','Euro','🇭🇷',true,true,'{"sports":{"confederation":"UEFA"}}'),
('HT','HTI','332','HAI','HAI','Haiti','{"es":"Haiti","en":"Haiti"}','{"es":"Republica de Haiti","en":"Republic of Haiti"}','Americas','Caribbean','NA','America/Port-au-Prince',array['America/Port-au-Prince'],'HTG','Haitian Gourde','🇭🇹',true,true,'{"sports":{"confederation":"CONCACAF"}}'),
('IR','IRN','364','IRN','IRI','Iran','{"es":"Iran","en":"Iran"}','{"es":"Republica Islamica de Iran","en":"Islamic Republic of Iran"}','Asia','Southern Asia','AS','Asia/Tehran',array['Asia/Tehran'],'IRR','Iranian Rial','🇮🇷',true,true,'{"sports":{"confederation":"AFC"}}'),
('IQ','IRQ','368','IRQ','IRQ','Irak','{"es":"Irak","en":"Iraq"}','{"es":"Republica de Irak","en":"Republic of Iraq"}','Asia','Western Asia','AS','Asia/Baghdad',array['Asia/Baghdad'],'IQD','Iraqi Dinar','🇮🇶',true,true,'{"sports":{"confederation":"AFC"}}'),
('CI','CIV','384','CIV','CIV','Costa de Marfil','{"es":"Costa de Marfil","en":"Ivory Coast","fr":"Cote d''Ivoire"}','{"es":"Republica de Costa de Marfil","en":"Republic of Cote d''Ivoire"}','Africa','Western Africa','AF','Africa/Abidjan',array['Africa/Abidjan'],'XOF','West African CFA Franc','🇨🇮',true,true,'{"sports":{"confederation":"CAF"},"aliases":["Ivory Coast","Cote d''Ivoire","Cote d Ivoire"]}'),
('JP','JPN','392','JPN','JPN','Japon','{"es":"Japon","en":"Japan"}','{"es":"Japon","en":"Japan"}','Asia','Eastern Asia','AS','Asia/Tokyo',array['Asia/Tokyo'],'JPY','Yen','🇯🇵',true,true,'{"sports":{"confederation":"AFC"}}'),
('JO','JOR','400','JOR','JOR','Jordania','{"es":"Jordania","en":"Jordan"}','{"es":"Reino Hachemita de Jordania","en":"Hashemite Kingdom of Jordan"}','Asia','Western Asia','AS','Asia/Amman',array['Asia/Amman'],'JOD','Jordanian Dinar','🇯🇴',true,true,'{"sports":{"confederation":"AFC"}}'),
('KR','KOR','410','KOR','KOR','Corea del Sur','{"es":"Corea del Sur","en":"South Korea"}','{"es":"Republica de Corea","en":"Republic of Korea"}','Asia','Eastern Asia','AS','Asia/Seoul',array['Asia/Seoul'],'KRW','Won','🇰🇷',true,true,'{"sports":{"confederation":"AFC"},"aliases":["Korea Republic","Republic of Korea"]}'),
('MA','MAR','504','MAR','MAR','Marruecos','{"es":"Marruecos","en":"Morocco"}','{"es":"Reino de Marruecos","en":"Kingdom of Morocco"}','Africa','Northern Africa','AF','Africa/Casablanca',array['Africa/Casablanca'],'MAD','Moroccan Dirham','🇲🇦',true,true,'{"sports":{"confederation":"CAF"}}'),
('MX','MEX','484','MEX','MEX','Mexico','{"es":"Mexico","en":"Mexico"}','{"es":"Estados Unidos Mexicanos","en":"United Mexican States"}','Americas','Central America','NA','America/Mexico_City',array['America/Mexico_City','America/Cancun','America/Tijuana','America/Monterrey'],'MXN','Mexican Peso','🇲🇽',true,true,'{"sports":{"confederation":"CONCACAF"}}'),
('NL','NLD','528','NED','NED','Paises Bajos','{"es":"Paises Bajos","en":"Netherlands"}','{"es":"Reino de los Paises Bajos","en":"Kingdom of the Netherlands"}','Europe','Western Europe','EU','Europe/Amsterdam',array['Europe/Amsterdam'],'EUR','Euro','🇳🇱',true,true,'{"sports":{"confederation":"UEFA"},"aliases":["Netherlands","Holland"]}'),
('NO','NOR','578','NOR','NOR','Noruega','{"es":"Noruega","en":"Norway"}','{"es":"Reino de Noruega","en":"Kingdom of Norway"}','Europe','Northern Europe','EU','Europe/Oslo',array['Europe/Oslo'],'NOK','Norwegian Krone','🇳🇴',true,true,'{"sports":{"confederation":"UEFA"}}'),
('NZ','NZL','554','NZL','NZL','Nueva Zelanda','{"es":"Nueva Zelanda","en":"New Zealand"}','{"en":"New Zealand"}','Oceania','Australia and New Zealand','OC','Pacific/Auckland',array['Pacific/Auckland','Pacific/Chatham'],'NZD','New Zealand Dollar','🇳🇿',true,true,'{"sports":{"confederation":"OFC"}}'),
('PA','PAN','591','PAN','PAN','Panama','{"es":"Panama","en":"Panama"}','{"es":"Republica de Panama","en":"Republic of Panama"}','Americas','Central America','NA','America/Panama',array['America/Panama'],'PAB','Panamanian Balboa','🇵🇦',true,true,'{"sports":{"confederation":"CONCACAF"}}'),
('PY','PRY','600','PAR','PAR','Paraguay','{"es":"Paraguay","en":"Paraguay"}','{"es":"Republica del Paraguay","en":"Republic of Paraguay"}','Americas','South America','SA','America/Asuncion',array['America/Asuncion'],'PYG','Paraguayan Guarani','🇵🇾',true,true,'{"sports":{"confederation":"CONMEBOL"}}'),
('PT','PRT','620','POR','POR','Portugal','{"es":"Portugal","en":"Portugal"}','{"es":"Republica Portuguesa","en":"Portuguese Republic"}','Europe','Southern Europe','EU','Europe/Lisbon',array['Europe/Lisbon','Atlantic/Madeira','Atlantic/Azores'],'EUR','Euro','🇵🇹',true,true,'{"sports":{"confederation":"UEFA"}}'),
('QA','QAT','634','QAT','QAT','Catar','{"es":"Catar","en":"Qatar"}','{"es":"Estado de Catar","en":"State of Qatar"}','Asia','Western Asia','AS','Asia/Qatar',array['Asia/Qatar'],'QAR','Qatari Rial','🇶🇦',true,true,'{"sports":{"confederation":"AFC"}}'),
('SA','SAU','682','KSA','KSA','Arabia Saudita','{"es":"Arabia Saudita","en":"Saudi Arabia"}','{"es":"Reino de Arabia Saudita","en":"Kingdom of Saudi Arabia"}','Asia','Western Asia','AS','Asia/Riyadh',array['Asia/Riyadh'],'SAR','Saudi Riyal','🇸🇦',true,true,'{"sports":{"confederation":"AFC"}}'),
('SN','SEN','686','SEN','SEN','Senegal','{"es":"Senegal","en":"Senegal"}','{"es":"Republica de Senegal","en":"Republic of Senegal"}','Africa','Western Africa','AF','Africa/Dakar',array['Africa/Dakar'],'XOF','West African CFA Franc','🇸🇳',true,true,'{"sports":{"confederation":"CAF"}}'),
('SE','SWE','752','SWE','SWE','Suecia','{"es":"Suecia","en":"Sweden"}','{"es":"Reino de Suecia","en":"Kingdom of Sweden"}','Europe','Northern Europe','EU','Europe/Stockholm',array['Europe/Stockholm'],'SEK','Swedish Krona','🇸🇪',true,true,'{"sports":{"confederation":"UEFA"}}'),
('CH','CHE','756','SUI','SUI','Suiza','{"es":"Suiza","en":"Switzerland"}','{"es":"Confederacion Suiza","en":"Swiss Confederation"}','Europe','Western Europe','EU','Europe/Zurich',array['Europe/Zurich'],'CHF','Swiss Franc','🇨🇭',true,true,'{"sports":{"confederation":"UEFA"}}'),
('TN','TUN','788','TUN','TUN','Tunez','{"es":"Tunez","en":"Tunisia"}','{"es":"Republica Tunecina","en":"Tunisian Republic"}','Africa','Northern Africa','AF','Africa/Tunis',array['Africa/Tunis'],'TND','Tunisian Dinar','🇹🇳',true,true,'{"sports":{"confederation":"CAF"}}'),
('TR','TUR','792','TUR','TUR','Turquia','{"es":"Turquia","en":"Turkiye"}','{"es":"Republica de Turquia","en":"Republic of Turkiye"}','Asia','Western Asia','AS','Europe/Istanbul',array['Europe/Istanbul'],'TRY','Turkish Lira','🇹🇷',true,true,'{"sports":{"confederation":"UEFA"},"aliases":["Turkey","Türkiye"]}'),
('US','USA','840','USA','USA','EE.UU.','{"es":"EE.UU.","en":"United States"}','{"es":"Estados Unidos de America","en":"United States of America"}','Americas','Northern America','NA','America/New_York',array['America/New_York','America/Chicago','America/Denver','America/Los_Angeles','America/Anchorage','Pacific/Honolulu'],'USD','US Dollar','🇺🇸',true,true,'{"sports":{"confederation":"CONCACAF"},"aliases":["USA","United States","United States of America","Estados Unidos"]}'),
('UY','URY','858','URU','URU','Uruguay','{"es":"Uruguay","en":"Uruguay"}','{"es":"Republica Oriental del Uruguay","en":"Oriental Republic of Uruguay"}','Americas','South America','SA','America/Montevideo',array['America/Montevideo'],'UYU','Uruguayan Peso','🇺🇾',true,true,'{"sports":{"confederation":"CONMEBOL"}}'),
('UZ','UZB','860','UZB','UZB','Uzbekistan','{"es":"Uzbekistan","en":"Uzbekistan"}','{"es":"Republica de Uzbekistan","en":"Republic of Uzbekistan"}','Asia','Central Asia','AS','Asia/Tashkent',array['Asia/Tashkent','Asia/Samarkand'],'UZS','Uzbekistani Som','🇺🇿',true,true,'{"sports":{"confederation":"AFC"}}'),
('ZA','ZAF','710','RSA','RSA','Sudafrica','{"es":"Sudafrica","en":"South Africa"}','{"es":"Republica de Sudafrica","en":"Republic of South Africa"}','Africa','Southern Africa','AF','Africa/Johannesburg',array['Africa/Johannesburg'],'ZAR','South African Rand','🇿🇦',true,true,'{"sports":{"confederation":"CAF"},"aliases":["South Africa","RSA"]}')
on conflict (code_alpha2) do update set
  code_alpha3 = excluded.code_alpha3,
  numeric_code = excluded.numeric_code,
  fifa_code = excluded.fifa_code,
  ioc_code = excluded.ioc_code,
  default_name = excluded.default_name,
  names = excluded.names,
  official_names = excluded.official_names,
  region = excluded.region,
  subregion = excluded.subregion,
  continent = excluded.continent,
  timezone_default = excluded.timezone_default,
  timezones = excluded.timezones,
  currency_code = excluded.currency_code,
  currency_name = excluded.currency_name,
  flag_emoji = excluded.flag_emoji,
  is_fifa_member = excluded.is_fifa_member,
  is_sovereign = excluded.is_sovereign,
  payload = excluded.payload,
  updated_at = now();

commit;
